# Generated by Django 5.1.3 on 2025-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHoursLoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('shop', models.CharField(max_length=256)),
                ('Time', models.CharField(max_length=256)),
                ('chengeTime', models.DateTimeField(auto_now_add=True)),
                ('chenge', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneLoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('shop', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('chengeTime', models.DateTimeField(auto_now_add=True)),
                ('chenge', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TitleLoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=256)),
                ('Time', models.CharField(max_length=256)),
                ('chengeTime', models.DateTimeField(auto_now_add=True)),
                ('chenge', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteLoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('shop', models.CharField(max_length=256)),
                ('Time', models.CharField(max_length=256)),
                ('chengeTime', models.DateTimeField(auto_now_add=True)),
                ('chenge', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
    ]
