# Generated by Django 5.1.3 on 2025-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openhoursloge',
            options={'ordering': ['-chengeTime']},
        ),
        migrations.AlterModelOptions(
            name='phoneloge',
            options={'ordering': ['-chengeTime']},
        ),
        migrations.AlterModelOptions(
            name='titleloge',
            options={'ordering': ['-chengeTime']},
        ),
        migrations.AlterModelOptions(
            name='websiteloge',
            options={'ordering': ['-chengeTime']},
        ),
        migrations.RenameField(
            model_name='openhoursloge',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='titleloge',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='websiteloge',
            old_name='Time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='openhoursloge',
            name='chenge',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='openhoursloge',
            table='google_open_hours_log',
        ),
        migrations.AlterModelTable(
            name='phoneloge',
            table='google_phone_log',
        ),
        migrations.AlterModelTable(
            name='titleloge',
            table='google_title_log',
        ),
        migrations.AlterModelTable(
            name='websiteloge',
            table='google_website_log',
        ),
    ]
