# Generated by Django 5.1.3 on 2025-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderyoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shop_id_company', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_url_company', models.CharField(blank=True, max_length=512, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=16, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=512, null=True)),
                ('serviceFee', models.CharField(blank=True, max_length=16, null=True)),
                ('deliveryFee', models.CharField(blank=True, max_length=16, null=True)),
                ('deliveryTime', models.CharField(blank=True, max_length=16, null=True)),
                ('takeAwayTime', models.CharField(blank=True, max_length=16, null=True)),
                ('ownerOrContactPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('hasDelivery', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'orderyoyo',
            },
        ),
    ]
