# Generated by Django 5.1.3 on 2025-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('areacd', models.TextField(primary_key=True, serialize=False)),
                ('areanm', models.TextField(blank=True, null=True)),
                ('parentcd', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'region',
            },
        ),
    ]
