# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodhub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=25, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=256, null=True)),
                ('places', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('town', models.CharField(blank=True, max_length=256, null=True)),
                ('region_state', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=64, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('host', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=512, null=True)),
                ('review_categories', models.CharField(blank=True, max_length=256, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=32, null=True)),
                ('collection_time', models.CharField(blank=True, max_length=32, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('android_link', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('keywords', models.CharField(blank=True, max_length=1024, null=True)),
                ('seo', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'foodhub',
            },
        ),
    ]
