# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foodhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=64, null=True)),
                ('latitude', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('region_state', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('social_media', models.CharField(blank=True, max_length=256, null=True)),
                ('apps', models.CharField(blank=True, max_length=256, null=True)),
                ('map_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'foodhouse',
            },
        ),
    ]
