# Generated by Django 5.1.3 on 2025-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhuse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhouse',
            name='apps',
        ),
        migrations.AddField(
            model_name='foodhouse',
            name='android_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodhouse',
            name='app_store_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
