# Generated by Django 5.1.3 on 2025-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('SuperUser', 'SuperUser'), ('Developer', 'Developer'), ('Marketing', 'Marketing'), ('Support', 'Support'), ('Onboarding', 'Onboarding'), ('Management', 'Management'), ('UX/UI', 'UX/UI')], max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('allowedChange', models.BooleanField(default=False)),
                ('getInfo', models.BooleanField(default=False)),
                ('googleBusiness', models.BooleanField(default=False)),
                ('device', models.BooleanField(default=False)),
                ('companies', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
