# Generated by Django 5.1.3 on 2025-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gbdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gbDashboardEdit',
            field=models.BooleanField(default=False),
        ),
    ]
