# Generated by Django 5.1.3 on 2025-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_gbdashboardedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gbDashboardCuontMap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gbDashboardCuontWeb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gbDashboardserchecunt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gbDashboardserchemap',
            field=models.BooleanField(default=False),
        ),
    ]
