# Generated by Django 5.1.3 on 2025-03-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_gbdashboardcuontmap_user_gbdashboardcuontweb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='limitedDisplay',
            new_name='gbDashboardKeywords',
        ),
    ]
