# Generated by Django 5.1.3 on 2025-03-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_limiteddisplay_user_gbdashboardkeywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allowedChange',
            new_name='gbKeywords',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gbDashboardCuontMap',
            new_name='gbMapCount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gbDashboardCuontWeb',
            new_name='gbSerchecunt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gbDashboardKeywords',
            new_name='gbWebCount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gbDashboardserchecunt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gbDashboardserchemap',
        ),
    ]
