# Generated by Django 5.1.3 on 2025-03-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_allowedchange_user_gbkeywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gbSerchecunt',
            new_name='gbDSerchecount',
        ),
    ]
