# Generated by Django 5.1.3 on 2025-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_gbserchecunt_user_gbdserchecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='device',
            new_name='devices',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gbDashboard',
            new_name='gbDashboardMap',
        ),
        migrations.AddField(
            model_name='user',
            name='gbDashboardPanel',
            field=models.BooleanField(default=False),
        ),
    ]
