# Generated by Django 5.1.3 on 2025-03-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_googlebusiness_user_googlebusinessmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gbDashboardPanel',
            new_name='googleBusinessPanel',
        ),
    ]
