# Generated by Django 5.1.3 on 2025-03-13 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_gbdashboardpanel_user_googlebusinesspanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_request',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
