# Generated by Django 5.1.3 on 2025-03-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_time_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='time_request',
            new_name='timeRequest',
        ),
        migrations.AddField(
            model_name='user',
            name='isLimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='numberOfRequest',
            field=models.IntegerField(default=0),
        ),
    ]
