# Generated by Django 5.1.3 on 2025-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_time_request_user_timerequest_user_islimited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refreshNumber',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='user',
            name='refreshTimeRequest',
            field=models.IntegerField(default=24, help_text='After the time is up, this time is added * in hours.'),
        ),
    ]
