# Generated by Django 5.1.3 on 2025-03-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_refreshnumber_user_refreshtimerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='numberOfRequest',
            new_name='numberOfRequestRemaining',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='refreshNumber',
            new_name='refreshNumberRequest',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='timeRequest',
            new_name='timeRequestRemaining',
        ),
    ]
