# Generated by Django 5.1.3 on 2025-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCodes',
            fields=[
                ('Postcode', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'postcodes',
            },
        ),
    ]
