# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=16, unique=True)),
                ('shop_name', models.CharField(blank=True, max_length=32, null=True)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('places', models.CharField(blank=True, max_length=16, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('region_state', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=32, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=16, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=256, null=True)),
                ('unique_name', models.CharField(blank=True, max_length=32, null=True)),
                ('is_new', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'justeat',
            },
        ),
    ]
