# Generated by Django 5.1.3 on 2025-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justeat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justeat',
            name='area',
        ),
        migrations.RemoveField(
            model_name='justeat',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='justeat',
            name='places',
        ),
        migrations.RemoveField(
            model_name='justeat',
            name='region_state',
        ),
        migrations.RemoveField(
            model_name='justeat',
            name='unique_name',
        ),
        migrations.AddField(
            model_name='justeat',
            name='city',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='justeat',
            name='county',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='justeat',
            name='region',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='justeat',
            name='shop_id',
            field=models.CharField(max_length=16),
        ),
    ]
