# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatTheFork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=16, unique=True)),
                ('shop_name', models.CharField(blank=True, max_length=32, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('places', models.CharField(blank=True, max_length=16, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('region_state', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('rating', models.CharField(blank=True, max_length=16, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=16, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=100, null=True)),
                ('url_map', models.CharField(blank=True, max_length=64, null=True)),
                ('map_preview_url', models.CharField(blank=True, max_length=64, null=True)),
                ('about_text', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('email_business', models.CharField(blank=True, max_length=32, null=True)),
                ('unique_name', models.CharField(blank=True, max_length=32, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=64, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=64, null=True)),
                ('google_play_link', models.CharField(blank=True, max_length=64, null=True)),
                ('app_store_link', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('main_text', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours_readable', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'whatthefork',
            },
        ),
    ]
