# Generated by Django 5.1.3 on 2025-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatthefork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatthefork',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='whatthefork',
            name='google_play_link',
        ),
        migrations.RemoveField(
            model_name='whatthefork',
            name='opening_hours_readable',
        ),
        migrations.RemoveField(
            model_name='whatthefork',
            name='places',
        ),
        migrations.RemoveField(
            model_name='whatthefork',
            name='url_map',
        ),
        migrations.AddField(
            model_name='whatthefork',
            name='android_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='whatthefork',
            name='city',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='whatthefork',
            name='map_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
