# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UberEats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=256, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=64, null=True)),
                ('longitude', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=16, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('city_slug', models.CharField(blank=True, max_length=64, null=True)),
                ('places', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('street_address', models.CharField(blank=True, max_length=128, null=True)),
                ('region_state', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('rating', models.CharField(blank=True, max_length=32, null=True)),
                ('total_reviews', models.CharField(blank=True, max_length=32, null=True)),
                ('cuisines', models.CharField(blank=True, max_length=256, null=True)),
                ('location_type', models.CharField(blank=True, max_length=64, null=True)),
                ('shop_name_unique', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'ubereats',
            },
        ),
    ]
