# Generated by Django 5.1.3 on 2025-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubereats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubereats',
            name='city_slug',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='country',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='places',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='region_state',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='shop_name_unique',
        ),
        migrations.RemoveField(
            model_name='ubereats',
            name='street_address',
        ),
        migrations.AddField(
            model_name='ubereats',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ubereats',
            name='county',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ubereats',
            name='cuisines',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
